[package]
name = "wh"
version = "1.6.0"
authors = ["insomnimus <insomnimus19@gmail.com>"]
edition = "2018"
include = [
"src/*",
"Cargo.toml",
"readme.md",
"LICENSE",
]
description= "A 'which' tool replacement."
repository = "https://github.com/insomnimus/wh"
keywords= ["cli", "tool"]
license= "MIT"
readme= "readme.md"

[[bin]]
name = "wh"
path = "src/main.rs"

[dependencies]
globset = "0.4.8"
ignore = "0.4.18"

[dependencies.clap]
version = "3.0.0-beta.5"
default-features = false
features = [
	"cargo",
	"std",
	"color",
	"suggestions",
	"unicode",
	"env",
]
