[package]
name = "wh"
description = "An extended alternative to GNU which"
version = "2.0.0"
authors = ["Taylan Gökkaya"]
include = [
	"src/*",
	"Cargo.toml",
	"Cargo.lock",
	"readme.md",
	"LICENSE",
]
edition = "2021"
repository = "https://github.com/insomnimus/wh"
keywords= ["cli", "tool"]
license= "MIT"
readme= "readme.md"

[profile.release]
lto = "thin"
panic = "abort"

[dependencies]
clap = { version = "4.2.4", features = ["derive"] }
globset = "0.4.10"
home = "0.5.4"

[target.'cfg(not(windows))'.dependencies]
atty = "0.2.14"
nom = "7.1.3"
