[package]
name = "wh"
version = "1.6.7"
authors = ["insomnimus <insomnimus19@gmail.com>"]
edition = "2018"
include = [
"src/*",
"Cargo.toml",
"readme.md",
"LICENSE",
]
description= "A 'which' tool replacement."
repository = "https://github.com/insomnimus/wh"
keywords= ["cli", "tool"]
license= "MIT"
readme= "readme.md"

[[bin]]
name = "wh"
path = "src/main.rs"

[dependencies]
globset = "0.4.8"
ignore = "0.4.18"
clap = { version = "3.0.0-rc.7", features = ["cargo", "env", "unicode", "wrap_help"] }
