[package]
name = "rs-which"
version = "0.1.0"
authors = ["insomnimus <insomnimus19@gmail.com>"]
edition = "2018"

[[bin]]
name = "wh"
path = "src/main.rs"

[dependencies]
clap = "2.33.3"
glob = "0.3.0"
