[package]
name = "wh"
version = "1.4.1"
authors = ["insomnimus <insomnimus19@gmail.com>"]
edition = "2018"
include = [
"src/*",
"Cargo.toml",
"readme.md",
"LICENSE",
]
description= "A 'which' tool replacement."
repository = "https://github.com/insomnimus/wh"
keywords= ["cli", "tool"]
license= "MIT"
readme= "readme.md"

[[bin]]
name = "wh"
path = "src/main.rs"

[dependencies]
clap = "3.0.0-beta.2"
glob = "0.3.0"
walkdir = "2.3.2"

[build-dependencies]
clap = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.2"
