[package]
name = "rs-which"
version = "1.0.0"
authors = ["insomnimus <insomnimus19@gmail.com>"]
edition = "2018"

[[bin]]
name = "wh"
path = "src/main.rs"

[dependencies]
glob = "0.3.0"
clap = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.2"
