{
  "name": "All",
  "on": [
    "push",
    "pull_request"
  ],
  "jobs": {
    "test": {
      "strategy": {
        "matrix": {
          "include": [
            {
              "os": "ubuntu-latest",
              "target": "x86_64-unknown-linux-gnu"
            },
            {
              "os": "macOS-11",
              "target": "x86_64-apple-darwin"
            },
            {
              "os": "windows-latest",
              "target": "x86_64-pc-windows-msvc"
            }
          ]
        }
      },
      "runs-on": "${{ matrix.os }}",
      "steps": [
        {
          "name": "Setup | Checkout",
          "uses": "actions/checkout@v3"
        },
        {
          "name": "Check | Tests",
          "run": "cargo test --target ${{ matrix.target }}"
        }
      ]
    },
    "build": {
      "name": "Build Release Binaries",
      "needs": "test",
      "if": "github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')",
      "continue-on-error": true,
      "strategy": {
        "fail-fast": false,
        "matrix": {
          "include": [
            {
              "target": "i686-pc-windows-msvc",
              "name": "wh-i686-pc-windows-msvc.zip",
              "os": "windows-latest"
            },
            {
              "target": "x86_64-pc-windows-msvc",
              "name": "wh-x86_64-pc-windows-msvc.zip",
              "os": "windows-latest"
            },
            {
              "target": "x86_64-unknown-linux-gnu",
              "name": "wh-x86_64-unknown-linux-gnu.tar.gz",
              "os": "ubuntu-latest"
            },
            {
              "target": "aarch64-unknown-linux-musl",
              "name": "wh-aarch64-unknown-linux-musl.tar.gz",
              "os": "ubuntu-latest"
            },
            {
              "target": "i686-unknown-linux-gnu",
              "name": "wh-i686-unknown-linux-gnu.tar.gz",
              "os": "ubuntu-latest"
            },
            {
              "target": "armv7-unknown-linux-gnueabihf",
              "name": "wh-armv7-unknown-linux-gnueabihf.tar.gz",
              "os": "ubuntu-latest"
            },
            {
              "target": "arm-unknown-linux-gnueabihf",
              "name": "wh-arm-unknown-linux-gnueabihf.tar.gz",
              "os": "ubuntu-latest"
            },
            {
              "target": "powerpc-unknown-linux-gnu",
              "name": "wh-powerpc-unknown-linux-gnu.tar.gz",
              "os": "ubuntu-latest"
            },
            {
              "target": "powerpc64-unknown-linux-gnu",
              "name": "wh-powerpc64-unknown-linux-gnu.tar.gz",
              "os": "ubuntu-latest"
            },
            {
              "target": "powerpc64le-unknown-linux-gnu",
              "name": "wh-powerpc64le-unknown-linux-gnu.tar.gz",
              "os": "ubuntu-latest"
            },
            {
              "target": "x86_64-apple-darwin",
              "name": "wh-x86_64-apple-darwin.tar.gz",
              "os": "macos-latest"
            },
            {
              "target": "x86_64-unknown-freebsd",
              "name": "wh-x86_64-unknown-freebsd.tar.gz",
              "os": "ubuntu-latest"
            },
            {
              "target": "x86_64-unknown-netbsd",
              "name": "wh-x86_64-unknown-netbsd.tar.gz",
              "os": "ubuntu-latest"
            }
          ]
        }
      },
      "runs-on": "${{ matrix.os }}",
      "steps": [
        {
          "name": "Setup | Checkout",
          "uses": "actions/checkout@v3"
        },
        {
          "name": "Setup | Cache Cargo",
          "uses": "actions/cache@v3",
          "with": {
            "path": "~/.cargo/registry\n~/.cargo/git\n",
            "key": "${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}"
          }
        },
        {
          "name": "Setup | rustup native",
          "if": "contains(matrix.target, 'windows')  || matrix.target == 'x86_64-unknown-linux-gnu' || contains(matrix.target, 'apple')",
          "run": "rustup default nightly-${{ matrix.target }}\nrustup component add rust-src"
        },
        {
          "name": "Setup | rustup and cross",
          "if": "!contains(matrix.target, 'windows') && matrix.target != 'x86_64-unknown-linux-gnu' && !contains(matrix.target, 'apple')",
          "run": "rustup default nightly\ncargo install cross"
        },
        {
          "name": "Build | Native",
          "if": "contains(matrix.target, 'windows')  || matrix.target == 'x86_64-unknown-linux-gnu' || contains(matrix.target, 'apple')",
          "run": "cargo rustc --release --target ${{ matrix.target }} -- -Ctarget-feature=+crt-static"
        },
        {
          "name": "Build | Cross",
          "if": "!contains(matrix.target, 'windows') && matrix.target != 'x86_64-unknown-linux-gnu' && !contains(matrix.target, 'apple')",
          "run": "cross rustc --release --target ${{ matrix.target }} -- -Ctarget-feature=+crt-static"
        },
        {
          "name": "PostBuild | Prepare",
          "if": "matrix.os != 'windows-latest'",
          "run": "cd target/${{ matrix.target }}/release\nstrip wh || true\ntar czvf ../../../${{ matrix.name }} wh\ncd -"
        },
        {
          "name": "PostBuild | Prepare",
          "if": "matrix.os == 'windows-latest'",
          "run": "cd target/${{ matrix.target }}/release\n7z a ../../../${{ matrix.name }} wh.exe\ncd -"
        },
        {
          "name": "Deploy | Upload Artifacts",
          "uses": "actions/upload-artifact@v3",
          "with": {
            "name": "${{ matrix.name }}",
            "path": "${{ matrix.name }}"
          }
        }
      ]
    },
    "release": {
      "name": "Create GitHub Release",
      "needs": "build",
      "if": "github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')",
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "name": "Setup | Checkout",
          "uses": "actions/checkout@v3",
          "with": {
            "fetch-depth": 0
          }
        },
        {
          "name": "Setup | go",
          "uses": "actions/setup-go@v4",
          "with": {
            "go-version": "^1.15.7"
          }
        },
        {
          "name": "Setup | Artifacts",
          "uses": "actions/download-artifact@v3"
        },
        {
          "name": "Setup | Release notes",
          "run": "GO111MODULE=on go install github.com/git-chglog/git-chglog/cmd/git-chglog@0.9.1\ngit-chglog -c .github/chglog/release.yml \"$(git describe --tags)\" > RELEASE.md"
        },
        {
          "name": "Deploy | Publish",
          "uses": "softprops/action-gh-release@v1",
          "with": {
            "files": "wh-*/wh-*",
            "body_path": "RELEASE.md"
          }
        }
      ]
    }
  }
}